version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: eventchain-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventchain_db
    volumes:
      - eventchain_postgres_data:/var/lib/postgresql/data

volumes:
  eventchain_postgres_data:
